[Forecasting: Principles and Practice](https://otexts.com/fpp2/)

In [44]:
from graph_traffic.merge_data import merge_data
from graph_traffic.config import data_path
import numpy as np
from sklearn.dummy import DummyRegressor

train = np.load(f"{data_path}/05-graph-data/001-dataset/001_train.npz")
x_train = train["x"]
y_train = train["y"][..., [0]].reshape(x_train.shape[0], -1)

valid = np.load(f"{data_path}/05-graph-data/001-dataset/001_valid.npz")
x_valid = valid["x"]
y_valid = valid["y"][..., [0]].reshape(x_valid.shape[0], -1)

test = np.load(f"{data_path}/05-graph-data/001-dataset/001_test.npz")
x_test = test["x"]
y_test = test["y"][..., [0]].reshape(x_test.shape[0], -1)

In [52]:
import numpy.ma as ma

In [69]:
x_train_ma = ma.masked_values(x_train, np.full_like(x_train, True))
y_train_ma = ma.masked_values(y_train, np.full_like(y_train, True))

In [70]:
mean_regr.fit(x_train_ma, y_train_ma)
mean_regr.score(x_valid, y_valid)

-1.7679330350929263

In [65]:
x_train_ma.mask

array([[[[False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False]],

        [[False,  True,  True, ..., False,  True, False],
         [ True,  True,  True, ..., False,  True, False],
         [ True,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False]],

        [[False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False]],

        ...,

        [[False, False, False, ..., False,  True, False],
         [False, False, False, ..., False,  True, Fa

In [64]:
x_train_ma[~x_train_ma.mask].data

array([6.70000000e+01, 1.00000000e+00, 3.00000000e+00, ...,
       2.08333333e-02, 1.00000000e+00, 1.00000000e+00])

## Average method

In [45]:
mean_regr = DummyRegressor(strategy="mean")
mean_regr.fit(x_train, y_train)
mean_regr.score(x_train, y_train)

0.0

In [46]:
mean_regr.score(x_valid, y_valid)

-1.7679330350929263

In [47]:
mean_regr.score(x_test, y_test)

-11.182149520044659

In [49]:
y_test

array([[  0.,   0.,   0., ...,   0.,   0.,  85.],
       [  0.,   0.,   0., ...,   0.,   0.,  34.],
       [  0.,   0.,   0., ...,   0.,   0.,  81.],
       ...,
       [  0., 511., 716., ..., 353., 315., 107.],
       [  0., 528., 730., ..., 321., 355., 163.],
       [  0., 364., 647., ..., 466., 424., 236.]])

In [40]:
x_train[:, :, :, 0].mean(axis=(0, 1))

array([456.85829329, 195.68119855, 180.39298941, 474.51482728,
       357.5595054 ])

In [38]:
x_train

array([[[[ 67.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 20.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 40.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 75.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 83.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ]],

        [[ 25.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [  0.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [  0.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 53.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 23.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ]],

        [[ 85.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 27.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 60.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [184.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [136.  