[Forecasting: Principles and Practice](https://otexts.com/fpp2/)

In [1]:
from graph_traffic.get_data import get_data
from graph_traffic.dataloading import npzDataset
from sklearn.dummy import DummyRegressor

data_dict = dict(
    ids_list=[3954, 3973, 3978],
    seq_len=12,
    with_graph=False,
    from_date="2020-01-01",
    to_date="2020-01-02",
    dataset_name="small",
    target="intensidad",  # 1
    interactions=None
)

meteo_dict = dict(
    rain="drop",  # 1
    wind="drop",  # 1
    temperature="drop",  # 0
    humidity="drop",  # 1
    pressure="drop",  # 0
    radiation="drop"  # 0
)

temporal_dict = dict(
    season="drop",  # 1
    month="drop",  # 6
    day_of_month="drop",  # 2
    hour="drop",  # 12,
    minute="drop",
    bank_holiday="drop",
    school_holiday="drop",
    working_day="drop"
)

x, y = get_data(data_dict, meteo_dict, temporal_dict)
dataset_name = data_dict["dataset_name"]
n_points = None

C:\Users\Bened\PycharmProjects\madrid-traffic\env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [10]:
train_data = npzDataset(dataset_name, "train", n_points)
test_data = npzDataset(dataset_name, "test", n_points)
valid_data = npzDataset(dataset_name, "valid", n_points)

In [11]:
print(train_data.x.shape)
print(train_data.y.shape)

(28, 12, 3, 1)
(28, 12, 3, 1)


In [24]:
x_train = train_data.x
y_train = train_data.y.reshape(x_train.shape[0], -1)

x_valid = valid_data.x
y_valid = valid_data.y.reshape(x_valid.shape[0], -1)

In [25]:
mean_regr = DummyRegressor(strategy="mean")
mean_regr.fit(x_train, y_train)
mean_regr.score(x_train, y_train)

0.0

In [26]:
import numpy as np

In [27]:
np.abs(mean_regr.predict(x_train) - y_train).mean()

44.52444727891156

In [28]:
np.abs(mean_regr.predict(x_valid) - y_valid).mean()

87.98690476190475

In [34]:
x_train[:, :, 0, 0]

array([[ 50.,  30.,  52., 189., 330., 492., 438., 629., 541., 465., 417.,
        293.],
       [ 30.,  52., 189., 330., 492., 438., 629., 541., 465., 417., 293.,
        225.],
       [ 52., 189., 330., 492., 438., 629., 541., 465., 417., 293., 225.,
        221.],
       [189., 330., 492., 438., 629., 541., 465., 417., 293., 225., 221.,
        137.],
       [330., 492., 438., 629., 541., 465., 417., 293., 225., 221., 137.,
        103.],
       [492., 438., 629., 541., 465., 417., 293., 225., 221., 137., 103.,
        121.],
       [438., 629., 541., 465., 417., 293., 225., 221., 137., 103., 121.,
        120.],
       [629., 541., 465., 417., 293., 225., 221., 137., 103., 121., 120.,
         91.],
       [541., 465., 417., 293., 225., 221., 137., 103., 121., 120.,  91.,
         97.],
       [465., 417., 293., 225., 221., 137., 103., 121., 120.,  91.,  97.,
        117.],
       [417., 293., 225., 221., 137., 103., 121., 120.,  91.,  97., 117.,
         73.],
       [293., 225., 2

In [42]:
np.mean(x_train, axis=(0, 3))

array([[202.53571429,  82.42857143, 190.25      ],
       [212.42857143,  85.32142857, 198.89285714],
       [219.42857143,  88.78571429, 206.42857143],
       [230.21428571,  92.        , 209.14285714],
       [237.03571429,  92.64285714, 211.25      ],
       [240.        ,  94.        , 215.21428571],
       [232.71428571,  91.67857143, 213.03571429],
       [229.32142857,  88.42857143, 202.57142857],
       [214.25      ,  80.64285714, 192.03571429],
       [202.21428571,  75.10714286, 180.07142857],
       [190.5       ,  69.57142857, 169.71428571],
       [177.85714286,  65.17857143, 162.        ]])

In [30]:
mean_regr.predict(x_valid)[0, :]

array([169.39285714,  61.64285714, 160.07142857, 162.53571429,
        59.5       , 157.39285714, 158.71428571,  58.35714286,
       153.57142857, 153.78571429,  57.42857143, 149.32142857,
       152.57142857,  55.67857143, 147.17857143, 148.57142857,
        54.85714286, 144.75      , 142.17857143,  53.82142857,
       142.75      , 138.60714286,  50.92857143, 136.57142857,
       137.5       ,  48.75      , 132.46428571, 132.25      ,
        48.14285714, 130.96428571, 132.42857143,  51.        ,
       133.32142857, 135.28571429,  53.14285714, 136.53571429])

In [40]:
mean_regr.predict(x_valid)[0, :]

array([169.39285714,  61.64285714, 160.07142857, 162.53571429,
        59.5       , 157.39285714, 158.71428571,  58.35714286,
       153.57142857, 153.78571429,  57.42857143, 149.32142857,
       152.57142857,  55.67857143, 147.17857143, 148.57142857,
        54.85714286, 144.75      , 142.17857143,  53.82142857,
       142.75      , 138.60714286,  50.92857143, 136.57142857,
       137.5       ,  48.75      , 132.46428571, 132.25      ,
        48.14285714, 130.96428571, 132.42857143,  51.        ,
       133.32142857, 135.28571429,  53.14285714, 136.53571429])

In [44]:
from graph_traffic.merge_data import merge_data
from graph_traffic.config import data_path
import numpy as np

train = np.load(f"{data_path}/05-graph-data/001-dataset/001_train.npz")
x_train = train["x"]
y_train = train["y"][..., [0]].reshape(x_train.shape[0], -1)

valid = np.load(f"{data_path}/05-graph-data/001-dataset/001_valid.npz")
x_valid = valid["x"]
y_valid = valid["y"][..., [0]].reshape(x_valid.shape[0], -1)

test = np.load(f"{data_path}/05-graph-data/001-dataset/001_test.npz")
x_test = test["x"]
y_test = test["y"][..., [0]].reshape(x_test.shape[0], -1)

In [52]:
import numpy.ma as ma

In [69]:
x_train_ma = ma.masked_values(x_train, np.full_like(x_train, True))
y_train_ma = ma.masked_values(y_train, np.full_like(y_train, True))

In [70]:
mean_regr.fit(x_train_ma, y_train_ma)
mean_regr.score(x_valid, y_valid)

-1.7679330350929263

In [65]:
x_train_ma.mask

array([[[[False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False]],

        [[False,  True,  True, ..., False,  True, False],
         [ True,  True,  True, ..., False,  True, False],
         [ True,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False]],

        [[False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False],
         [False,  True,  True, ..., False,  True, False]],

        ...,

        [[False, False, False, ..., False,  True, False],
         [False, False, False, ..., False,  True, Fa

In [64]:
x_train_ma[~x_train_ma.mask].data

array([6.70000000e+01, 1.00000000e+00, 3.00000000e+00, ...,
       2.08333333e-02, 1.00000000e+00, 1.00000000e+00])

## Average method

In [45]:
mean_regr = DummyRegressor(strategy="mean")
mean_regr.fit(x_train, y_train)
mean_regr.score(x_train, y_train)

0.0

In [46]:
mean_regr.score(x_valid, y_valid)

-1.7679330350929263

In [47]:
mean_regr.score(x_test, y_test)

-11.182149520044659

In [49]:
y_test

array([[  0.,   0.,   0., ...,   0.,   0.,  85.],
       [  0.,   0.,   0., ...,   0.,   0.,  34.],
       [  0.,   0.,   0., ...,   0.,   0.,  81.],
       ...,
       [  0., 511., 716., ..., 353., 315., 107.],
       [  0., 528., 730., ..., 321., 355., 163.],
       [  0., 364., 647., ..., 466., 424., 236.]])

In [40]:
x_train[:, :, :, 0].mean(axis=(0, 1))

array([456.85829329, 195.68119855, 180.39298941, 474.51482728,
       357.5595054 ])

In [38]:
x_train

array([[[[ 67.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 20.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 40.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 75.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 83.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ]],

        [[ 25.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [  0.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [  0.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 53.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 23.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ]],

        [[ 85.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 27.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [ 60.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [184.   ,   0.   ,   0.   , ...,   1.   ,   0.   ,   1.   ],
         [136.  